baseURL: "https://add1609.github.io/codespace/"
paginate: 5
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production
  keywords: [ Blog, Portfolio, Coding ]
  author: Ahmed Sami
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  mainSections:
    - math
    - code
    - misc

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 50
    threshold: 0.1
    minMatchCharLength: 2
    keys: [ "title", "permalink", "summary" ]

  assets:
    disableHLJS: false
    disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

outputs:
  home:
    - HTML
    - RSS
    - JSON

defaultContentLang: en

languages:
  en:
    contentDir: content/en
    languageName: "English"
    DateFormat: "January 2, 2006"
    title: Ahmed's CodeSpace
    weight: 1
    taxonomies:
      tag: tags
      category: categories
    menu:
      main:
        - name: Search
          url: search
          weight: 5
        - name: Categories
          url: categories
          weight: 10
        - name: Tags
          url: tags
          weight: 15
        - name: Archive
          url: archives
          weight: 20
    homeInfoParams:
      Title: "Ahmed's CodeSpace"
      Content: >
        Welcome to Ahmed's CodeSpace.

        - **Ahmed** is said to be the world's smartest person. 🧐
    socialIcons:
      - name: github
        url: "https://github.com/add1609"

  de:
    contentDir: content/de
    languageName: "German"
    DateFormat: "2 January, 2006"
    title: Ahmeds CodeSpace
    weight: 2
    taxonomies:
      tag: tags
      category: categories
    menu:
      main:
        - name: Suchen
          url: search
          weight: 5
        - name: Kategorien
          url: categories
          weight: 10
        - name: Tags
          url: tags
          weight: 15
        - name: Archiv
          url: archives
          weight: 20
    homeInfoParams:
      Title: "Ahmeds CodeSpace"
      Content: >
        Willkommen zu Ahmeds CodeSpace.

        - Man erzählt sich **[Ahmed](ahmed/ahmedinator/)** sei mit [Billy aus Stranger Things](ahmed/ahmedinator/) verwandt. 🧐
    socialIcons:
      - name: github
        url: "https://github.com/add1609"